### ISSUE TITLE
About the keyword

### ISSUE THREAD

**Issue by YouTheApple** [JJuOn/paper-crawler#2]
Hello, what should I set for keywords such as NeurIPS2022?

**Comment by JJuOn** [comment]
Hi, if you want to search for papers with the keyword "deep" in NeurIPS 2022, type the command as below:

`python main.py -c neurips -y 2022 -k deep`

We also support for searching with multiple keywords like:

`python main.py -c neurips -y 2022 -k deep neural`

The above command search papers which contain the keyword "deep" or "neural" in their title.
